---

- name: install and start nginx
  block:
    - name: install nginx
      yum:
        name: nginx
        state: present
      become: True

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
      become: True

