---
- name: install pip and PyMySQL
  block:
    - name: install python3-pip
      yum:
        name: "{{ item }}"
        state: present
      loop:
          - python3-pip
          - zip

    - name: install PyMySQL
      pip:
        name: pymysql